/*
 * action types
 */

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'

export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'

//export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'